export enum ROUTER {
    LIST_CUSTOMER = 'customer/list',
    CREATE_CUSTOMER = 'customer/create',
    EDIT_CUSTOMER = 'customer/edit',
    DETAIL_CUSTOMER = 'customer/detail',
    LOGIN = 'auth/login',
    LIST_EMPLOYEE = 'employee/list',
    EDIT_EMPLOYEE = 'employee/edit/',
    CREATE_EMPLOYEE = 'employee/create',
    FORGOT_PASSWORD = 'auth/forgotpassword',
    CHANGE_PASSWORD = 'auth/changepassword',
    RESET_PASSWORD = 'auth/reset-password',
    SIGNUP = 'auth/register',
    LANDING = 'landing',
    AUTH_ERROR = 'auth/error',
    LIST_WORK_SHIFT = 'work-shift/list',
}
